version: '3'
services:
  app:
    build: .
    user: node
    working_dir: /home/node/app
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/node/app
    depends_on:
      - "db"
    networks:
      - app-network
    command: "npm start"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      # MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:$DB_PORT'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db:

