version: '3'
services:
  app:
    build: .
    command: npm start
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - "db"
    networks:
      - app-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      # MYSQL_USER: $DB_USER
      # MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ./db/var:/var/lib/mysql
    ports:
      - '3306:$DB_PORT'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db:
